spring:
  zipkin:
    base-url: http://m2rs-zipkin-service-domain:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
    jdbc:
      p6spy:
        enable-logging: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://m2rs-db-service-domain:3306/m2rs_db
    username: m2rs
    password: '{cipher}AQABRZqIYkH+ctKu4jcpV/SMYgaah2LvQm3MFFjqLsvT0HWi2jLuKLiGUTikqlGUS3ZnsHHBvNaqUYxInYrtPo2rJ9EOOpMIRfsDkkOpFA4T1Q2gj+i6oiS4FAt7oesbbnrBZ8U2hf7yUKHKiCYsqXjPyS/tmP5wAAJBft9/m3aCAwUuCl9fJE4rwyQB/zgySBbrTO+e9ESty9H8/wgCpumow+PmFevlLcYjOy67DoZyj1fyIlSHwzG73OgCOdxIU07sMu0RWxa/NBrFfyk4l10S+qnJf6TmuoSjdcy2OQT/4Df4ZYpxwHAGv4jeOxeMhEyAJFOxw1el/H/FXmluYMbb7oxeBi3ZrsSEicQ2rYFdeNahTW0ZhRT+fJXwzgB3E/E='
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true


# user
user:
  company:
    logo-dir: ~/m2rs/logo
